server:
  port: 8081
spring:
  application:
    name: gateway
#是否与服务发现组件进行结合，通过 serviceId 转发到具体的服务实例。默认为false，设为true便开启通过服务中心的自动根据 serviceId 创建路由的功能。
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
        enabled: true
        register: true
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
      routes:
      - id: 163_route
        uri: https://www.163.com/
        predicates:
        - Path=/163/**

# 访问http://localhost:8081/163, 路由转发到 http://www.163.com